name: test

on:
  workflow_dispatch:

jobs:
  dispatch_reusable_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Reusable Workflow
        run: |
          gh workflow run msargent-dev/dynamic-exec/blob/staging/.github/workflows/concurrency-dispatch.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure necessary permissions
